modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/MC-U-Team/Overworld-Mirror/issues"
displayURL="https://u-team.info/mods/overworldmirror"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="overworldmirror"
	version="${file.jarVersion}"
	displayName="Overworld Mirror"
	updateJSONURL="https://api.u-team.info/update/overworldmirror.json"
	description="This mod just mirrors the overworld and let you travel with a portal between them."
	
	[[dependencies.overworldmirror]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36.1.12,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.overworldmirror]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.overworldmirror]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.2.1.195,)"
	    ordering="NONE"
	    side="BOTH"