modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/MC-U-Team/Overworld-Mirror/issues"
displayURL="https://u-team.info/mods/overworldmirror"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="overworldmirror"
	version="${file.jarVersion}"
	displayName="Overworld Mirror"
	updateJSONURL="https://api.u-team.info/update/overworldmirror.json"
	description="This mod just mirrors the overworld and let you travel with a portal between them."
	
	[[dependencies.overworldmirror]]
	    modId="forge"
	    mandatory=true
	    versionRange="[43.2.0,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.overworldmirror]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.19.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.overworldmirror]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[4.4.2.234,)"
	    ordering="NONE"
	    side="BOTH"